package com.luzatuvida.lolatvadminandroid.global;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class baseDeDatos extends SQLiteOpenHelper {

    public baseDeDatos(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {

        db.execSQL("CREATE TABLE MENSAJES(ID TEXT, DESCRIPCION TEXT, FECHALIMITE TEXT, NUMINTENTOS TEXT, MAXINTENTOS TEXT)");

        db.execSQL("CREATE TABLE USERS(ID TEXT, ROL_ID TEXT, NAME TEXT)");
        db.execSQL("CREATE TABLE ZONAS(ID TEXT, ZONA TEXT)");
        db.execSQL("CREATE TABLE CONTRATOS(ID_CONTRATO TEXT, DATOS TEXT," +
                " ID_USUARIOCREACION TEXT, NOMBRE_USUARIOCREACION TEXT, ID_ZONA TEXT, NOMBRE TEXT," +
                " CALLE TEXT, NUMERO TEXT, DEPTO TEXT, ALLADODE TEXT, FRENTEA TEXT," +
                " ENTRECALLES TEXT, COLONIA TEXT, LOCALIDAD TEXT, TELEFONO TEXT, TELEFONOREFERENCIA TEXT," +
                " NOMBREREFERENCIA TEXT, CASATIPO TEXT, CASACOLOR TEXT, FOTOINEFRENTE TEXT, FOTOINEATRAS TEXT," +
                " FOTOCASA TEXT, COMPROBANTEDOMICILIO TEXT, ID_OPTOMETRISTA TEXT, TARJETAFRENTE TEXT," +
                " TARJETAATRAS TEXT, PAGO TEXT, ID_PROMOCION TEXT, TOTAL TEXT, IDCONTRATORELACION TEXT, CONTADOR TEXT, TOTALHISTORIAL TEXT, TOTALPROMOCION TEXT," +
                " TOTALPRODUCTO TEXT, TOTALABONO TEXT, ULTIMOABONO TEXT, ESTATUS_ESTADOCONTRATO TEXT, DIAPAGO TEXT," +
                " FECHACOBROINI TEXT, FECHACOBROFIN TEXT, FECHAATRASO TEXT, COSTOATRASO TEXT, DIASELECCIONADO TEXT, FECHAENTREGA TEXT, PAGOSADELANTAR TEXT," +
                " ENGANCHE TEXT, ENTREGAPRODUCTO TEXT, CORREO TEXT, ESTATUS TEXT, ENVIADOPAGINA TEXT, PAGARE TEXT, FOTOOTROS TEXT, PROMOCIONTERMINADA TEXT," +
                " SUBSCRIPCION TEXT, FECHASUBSCRIPCION TEXT, NOTA TEXT, TOTALREAL TEXT, DIATEMPORAL TEXT, COORDENADAS TEXT, CALLEENTREGA TEXT, NUMEROENTREGA TEXT," +
                " DEPTOENTREGA TEXT, ALLADODEENTREGA TEXT, FRENTEAENTREGA TEXT, ENTRECALLESENTREGA TEXT, COLONIAENTREGA TEXT, LOCALIDADENTREGA TEXT," +
                " CASATIPOENTREGA TEXT, CASACOLORENTREGA TEXT, ALIAS TEXT, REFERENCIA TEXT, OPCIONLUGARENTREGA TEXT," +
                " OBSERVACIONFOTOINE TEXT, OBSERVACIONFOTOINEATRAS TEXT, OBSERVACIONFOTOCASA TEXT, OBSERVACIONCOMPROBANTEDOMICILIO TEXT," +
                " OBSERVACIONPAGARE TEXT, OBSERVACIONFOTOOTROS TEXT, CREATED_AT TEXT, UPDATED_AT TEXT, " +
                " NOMBREPAQUETE TEXT, TITULOPROMOCION TEXT, CONTRATOENVIADO TEXT, ABONOMINIMO TEXT, AUTORIZACION TEXT)");

        db.execSQL("CREATE TABLE PROMOCION(ID TEXT, TITULO TEXT, PRECIOP TEXT, INICIO TEXT, FIN TEXT," +
                " STATUS TEXT, ASIGNADO TEXT, ID_TIPOPROMOCIONUSUARIO TEXT, CONTADO TEXT, ARMAZONES TEXT, TIPOPROMOCION TEXT, PRECIOUNO TEXT)");

        db.execSQL("CREATE TABLE HISTORIALCLINICO(ID TEXT, ID_CONTRATO TEXT, EDAD TEXT, FECHAENTREGA TEXT, DIAGNOSTICO TEXT," +
                " OCUPACION TEXT, DIABETES TEXT, HIPERTENSION TEXT, DOLOR TEXT, ARDOR TEXT, GOLPEOJOS TEXT, OTROM TEXT, MOLESTIAOTRO TEXT, ULTIMOEXAMEN TEXT," +
                " ESFERICODER TEXT, CILINDRODER TEXT, EJEDER TEXT, ADDDER TEXT, ALTDER TEXT, ESFERICOIZQ TEXT, CILINDROIZQ TEXT, EJEIZQ TEXT," +
                " ADDIZQ TEXT, ALTIZQ TEXT, ID_PRODUCTO TEXT, ID_PAQUETE TEXT, MATERIAL TEXT, MATERIALOTRO TEXT, COSTOMATERIAL TEXT, BIFOCAL TEXT," +
                " FOTOCROMATICO TEXT, AR TEXT, TINTE TEXT, BLUERAY TEXT, OTROT TEXT, TRATAMIENTOOTRO TEXT, COSTOTRATAMIENTO TEXT," +
                " OBSERVACIONES TEXT, OBSERVACIONESINTERNO TEXT, TIPO TEXT, BIFOCALOTRO TEXT, COSTOBIFOCAL TEXT, EMBARAZADA TEXT," +
                " DURMIOSEISOCHOHORAS TEXT, ACTIVIDADDIA TEXT, PROBLEMASOJOS TEXT, POLICARBONATOTIPO TEXT, ID_TRATAMIENTOCOLORTINTE TEXT, ESTILOTINTE TEXT, POLARIZADO TEXT," +
                " ID_TRATAMIENTOCOLORPOLARIZADO TEXT, ESPEJO TEXT, ID_TRATAMIENTOCOLORESPEJO TEXT, FOTOARMAZON TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE PRODUCTO(ID TEXT, ID_TIPOPRODUCTO TEXT, NOMBRE TEXT, PIEZAS TEXT, PRECIO TEXT, FOTO TEXT," +
                " COLOR TEXT, ESTADO TEXT, INICIOP TEXT, FINP TEXT, PRECIOP TEXT, ACTIVO TEXT, PREMIUM TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE PAQUETES(ID TEXT, NOMBRE TEXT, PRECIO TEXT)");

        db.execSQL("CREATE TABLE TRATAMIENTOS(ID TEXT, NOMBRE TEXT, PRECIO TEXT)");

        db.execSQL("CREATE TABLE PROMOCIONCONTRATO(ID TEXT, ID_CONTRATO TEXT, ID_PROMOCION TEXT, ESTADO TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE CONTRATOPRODUCTO(ID TEXT, ID_CONTRATO TEXT, ID_PRODUCTO TEXT, PIEZAS TEXT, TOTAL TEXT, ID_USUARIO TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE ABONOS(ID TEXT, ID_CONTRATO TEXT, ABONO TEXT, FOLIO TEXT, TIPOABONO TEXT, ATRASO TEXT, ADELANTOS TEXT, ID_USUARIO TEXT, METODOPAGO TEXT, CORTE TEXT," +
                " ENVIADOPAGINA TEXT, ID_CONTRATOPRODUCTO TEXT, COORDENADAS TEXT, CREATED_AT TEXT, UPDATED_AT TEXT, ENVIADO TEXT, POLIZA TEXT)");

        db.execSQL("CREATE TABLE HISTORIALCONTRATO(ID TEXT, ID_CONTRATO TEXT, ID_USUARIOC TEXT, CAMBIOS TEXT, TIPOMENSAJE TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE MOVIL(ID TEXT, USUARIO TEXT, CORREO TEXT, CONTRASENA TEXT, TOKEN TEXT, ROL TEXT, ID_ZONA TEXT, FECHAACTUAL TEXT, USUARIOLOGEADO TEXT, SUCURSAL TEXT," +
                " TOTALCONTRATOSCONABONO TEXT, JSONABONOSGENERAL TEXT, ULTIMOCONTRATO TEXT, TELEFONOATENCIONCLIENTESSUCURSAL TEXT, ID_FRANQUICIA TEXT," +
                " RUTA_FTP TEXT, USUARIO_FTP TEXT, CONTRASENA_FTP, WHATSAPP TEXT, ABONOMINIMOSEMANAL TEXT, PRECIODOLAR TEXT, SUPERVISORCOBRANZA TEXT, ULTIMACONEXION TEXT)");

        db.execSQL("CREATE TABLE ABONOSELIMINADOS(ID_CONTRATO TEXT, ID_ABONO TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT)");

        db.execSQL("CREATE TABLE PRODUCTOSELIMINADOS(ID_CONTRATO TEXT, ID_CONTRATOPRODUCTO TEXT, ID_PRODUCTO TEXT, PIEZAS TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT)");

        db.execSQL("CREATE TABLE PROMOCIONESELIMINADAS(ID_CONTRATO TEXT, ID_PROMOCIONCONTRATO TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT)");

        db.execSQL("CREATE TABLE GLOBAL(ID TEXT, DESCARGACOMPLETA TEXT, SUBIRIMAGENESFTP TEXT, SUBIRIMAGENESSUPERVISIONFTP TEXT)");
        db.execSQL("INSERT INTO GLOBAL VALUES('1', '0', '0', '0')");

        db.execSQL("CREATE TABLE IMAGENESCARGADASCONTRATOS(ID_CONTRATO TEXT, FOTOINE TEXT, FOTOINEATRAS TEXT, FOTOCASA TEXT, COMPROBANTEDOMICILIO TEXT, PAGARE TEXT, TARJETAPENSION TEXT," +
                " TARJETAPENSIONATRAS TEXT, FOTOOTROS TEXT, FOTOMOVIMIENTO TEXT, FOTOARMAZON1 TEXT, FOTOARMAZON2 TEXT)");

        db.execSQL("CREATE TABLE PAYMENTS(PAYMENT_ID TEXT, PAYER_EMAIL TEXT, ID_ABONO TEXT, AMOUNT TEXT, CURRENCY TEXT, PAYMENT_STATUS TEXT, TIPOORIGEN TEXT, ENVIADOPAGINA TEXT," +
                " CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE DATOSSTRIPE(ID_CONTRATO TEXT, ID_PAYMENTINTENT TEXT, ID_PAYMENTMETHOD TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE GARANTIAS(ID TEXT, ID_CONTRATO TEXT, ID_HISTORIAL TEXT, ID_HISTORIALGARANTIA TEXT, ID_OPTOMETRISTA TEXT, ESTADOGARANTIA TEXT, ENVIADOPAGINA TEXT," +
                " CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE RUTA(ID TEXT, DIA TEXT, ID_CONTRATO TEXT, ID_USUARIO TEXT, POSICION TEXT, ESTADO TEXT, ENVIADOPAGINA TEXT)");

        db.execSQL("CREATE TABLE CONTRATOSLIOSFUGAS(ID_CONTRATO TEXT, NOMBRE TEXT, COLONIA TEXT, CALLE TEXT, NUMERO TEXT, TELEFONO TEXT, CAMBIOS TEXT)");

        db.execSQL("CREATE TABLE HISTORIALSINCONVERSION(ID_CONTRATO TEXT, ID_HISTORIAL TEXT, ESFERICODER TEXT, CILINDRODER TEXT, EJEDER TEXT, ADDDER TEXT, ESFERICOIZQ TEXT," +
                " CILINDROIZQ TEXT, EJEIZQ TEXT, ADDIZQ TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT)");

        db.execSQL("CREATE TABLE LLAVES(LLAVE TEXT, TIPO TEXT)");

        db.execSQL("CREATE TABLE VENTAS(NOMBRE TEXT, ID_USUARIO TEXT, ROL TEXT, NUMEROVENTAS TEXT, SUCURSAL TEXT)");

        db.execSQL("CREATE TABLE CONFIGURACIONMOVIL(INDICE TEXT, FOTOLOGO TEXT, COLORICONOS TEXT, COLORENCABEZADOS TEXT, COLORNAVBAR TEXT, ESTADOCONFIGURACION TEXT)");

        db.execSQL("CREATE TABLE BUZON(INDICE TEXT, ID_USUARIO TEXT, ID_FRANQUICIA TEXT, MENSAJE TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE AUTORIZACIONESARMAZON(ID_CONTRATO TEXT, ID_PRODUCTO TEXT, FOLIOPOLIZA TEXT, ID_USUARIOC TEXT, TIPO TEXT, PIEZAS TEXT," +
                " ENVIADOPAGINA TEXT, CREATED_AT TEXT)");

        db.execSQL("CREATE TABLE COLONIAS(INDICE TEXT, ID_ZONA TEXT, COLONIA TEXT, LOCALIDAD TEXT, BANDERA TEXT)");

        db.execSQL("CREATE TABLE HISTORIALFOTOSCONTRATO(ID TEXT, ID_CONTRATO TEXT, ID_USUARIOC TEXT, FOTO TEXT, OBSERVACIONES TEXT, TIPOMENSAJE TEXT, ENVIADOPAGINA TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE VEHICULOSSUPERVISION(INDICE TEXT, ID_FRANQUICIA TEXT, ID_USUARIO TEXT, ID_VEHICULO TEXT, NUMSERIE TEXT, ESTADO TEXT, KILOMETRAJE1 TEXT, KILOMETRAJE2 TEXT, LADOIZQUIERDO TEXT," +
                " LADODERECHO TEXT, FRENTE TEXT, ATRAS TEXT, EXTRA1 TEXT, EXTRA2 TEXT, EXTRA3 TEXT, EXTRA4 TEXT, EXTRA5 TEXT, EXTRA6 TEXT, CREATED_AT TEXT, UPDATED_AT TEXT)");

        db.execSQL("CREATE TABLE IMAGENESCARGADASSUPERVISION(INDICE_SUPERVISION TEXT, KILOMETRAJE1 TEXT, KILOMETRAJE2 TEXT, LADOIZQUIERDO TEXT," +
                " LADODERECHO TEXT, FRENTE TEXT, ATRAS TEXT, EXTRA1 TEXT, EXTRA2 TEXT, EXTRA3 TEXT, EXTRA4 TEXT, EXTRA5 TEXT, EXTRA6 TEXT)");

        db.execSQL("CREATE TABLE TRATAMIENTOSCOLORES(INDICE TEXT, ID_TRATAMIENTO TEXT, COLOR TEXT)");

        db.execSQL("CREATE TABLE IMAGENESPENDIENTESMOVIL(NOMBREFOTO TEXT, BANDERA TEXT)");

        db.execSQL("CREATE TABLE IMAGENESSERVIDORCONTRATOS(ID_CONTRATO TEXT, FOTOINEFRENTE TEXT, FOTOINEATRAS TEXT, FOTOCASA TEXT, COMPROBANTEDOMICILIO TEXT, PAGARE TEXT, FOTOOTROS TEXT)");

        db.execSQL("CREATE TABLE CONTRATOSLISTANEGRA(ID_CONTRATO TEXT, DESCRIPCION TEXT, ESTADO TEXT, ENVIADOPAGINA TEXT)");

        db.execSQL("CREATE TABLE NOTASCOBRANZA(ID TEXT, NOTA TEXT, CREATED_AT TEXT, ENVIADOPAGINA TEXT, BANDERAELIMINADO TEXT)");

        db.execSQL("CREATE TABLE ASISTENCIA(ID_USUARIO TEXT, NOMBRE TEXT, ASISTENCIA TEXT, REGISTROSALIDA TEXT, ENVIADOPAGINA TEXT)");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if(newVersion > oldVersion){
            //Si nueva version es mayor a la version antigua
            eliminarTodasLasTablasSQLite(db); //Eliminar tablas de la base de datos
            onCreate(db); //Volverlas a crear las tablas
        }
    }

    private void eliminarTodasLasTablasSQLite(SQLiteDatabase db) {
        db.execSQL("DROP TABLE IF EXISTS MENSAJES");
        db.execSQL("DROP TABLE IF EXISTS USERS");
        db.execSQL("DROP TABLE IF EXISTS ZONAS");
        db.execSQL("DROP TABLE IF EXISTS CONTRATOS");
        db.execSQL("DROP TABLE IF EXISTS PROMOCION");
        db.execSQL("DROP TABLE IF EXISTS HISTORIALCLINICO");
        db.execSQL("DROP TABLE IF EXISTS PRODUCTO");
        db.execSQL("DROP TABLE IF EXISTS PAQUETES");
        db.execSQL("DROP TABLE IF EXISTS TRATAMIENTOS");
        db.execSQL("DROP TABLE IF EXISTS PROMOCIONCONTRATO");
        db.execSQL("DROP TABLE IF EXISTS CONTRATOPRODUCTO");
        db.execSQL("DROP TABLE IF EXISTS ABONOS");
        db.execSQL("DROP TABLE IF EXISTS HISTORIALCONTRATO");
        db.execSQL("DROP TABLE IF EXISTS MOVIL");
        db.execSQL("DROP TABLE IF EXISTS ABONOSELIMINADOS");
        db.execSQL("DROP TABLE IF EXISTS PRODUCTOSELIMINADOS");
        db.execSQL("DROP TABLE IF EXISTS PROMOCIONESELIMINADAS");
        db.execSQL("DROP TABLE IF EXISTS GLOBAL");
        db.execSQL("DROP TABLE IF EXISTS IMAGENESCARGADASCONTRATOS");
        db.execSQL("DROP TABLE IF EXISTS PAYMENTS");
        db.execSQL("DROP TABLE IF EXISTS DATOSSTRIPE");
        db.execSQL("DROP TABLE IF EXISTS GARANTIAS");
        db.execSQL("DROP TABLE IF EXISTS RUTA");
        db.execSQL("DROP TABLE IF EXISTS CONTRATOSLIOSFUGAS");
        db.execSQL("DROP TABLE IF EXISTS HISTORIALSINCONVERSION");
        db.execSQL("DROP TABLE IF EXISTS LLAVES");
        db.execSQL("DROP TABLE IF EXISTS VENTAS");
        db.execSQL("DROP TABLE IF EXISTS CONFIGURACIONMOVIL");
        db.execSQL("DROP TABLE IF EXISTS BUZON");
        db.execSQL("DROP TABLE IF EXISTS AUTORIZACIONESARMAZON");
        db.execSQL("DROP TABLE IF EXISTS COLONIAS");
        db.execSQL("DROP TABLE IF EXISTS HISTORIALFOTOSCONTRATO");
        db.execSQL("DROP TABLE IF EXISTS VEHICULOSSUPERVISION");
        db.execSQL("DROP TABLE IF EXISTS IMAGENESCARGADASSUPERVISION");
        db.execSQL("DROP TABLE IF EXISTS TRATAMIENTOSCOLORES");
        db.execSQL("DROP TABLE IF EXISTS IMAGENESPENDIENTESMOVIL");
        db.execSQL("DROP TABLE IF EXISTS IMAGENESSERVIDORCONTRATOS");
        db.execSQL("DROP TABLE IF EXISTS CONTRATOSLISTANEGRA");
        db.execSQL("DROP TABLE IF EXISTS NOTASCOBRANZA");
        db.execSQL("DROP TABLE IF EXISTS ASISTENCIA");
    }
}
